# Generated by Django 2.1.4 on 2018-12-16 12:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cedente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_cnpj', models.IntegerField()),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('cpf_cnpj',),
            },
        ),
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('vencimento', models.DateField()),
                ('documento', models.IntegerField()),
                ('valor_multa', models.FloatField()),
                ('valor_juros', models.FloatField()),
                ('parcela', models.IntegerField()),
                ('cedente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedente', to='dividas.Cedente')),
            ],
            options={
                'ordering': ('sacado_id',),
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cep', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=60)),
                ('logradouro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sacado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.IntegerField()),
                ('nome', models.CharField(max_length=60)),
                ('endereco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividas.Endereco')),
            ],
            options={
                'ordering': ('cpf',),
            },
        ),
        migrations.AddField(
            model_name='divida',
            name='sacado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacado', to='dividas.Sacado'),
        ),
        migrations.AddField(
            model_name='cedente',
            name='endereco_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividas.Endereco'),
        ),
    ]
