# Generated by Django 2.1.4 on 2018-12-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='cedente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividas.Cedente'),
        ),
        migrations.AlterField(
            model_name='divida',
            name='documento',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='divida',
            name='sacado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividas.Sacado'),
        ),
    ]
