# Generated by Django 2.1.4 on 2018-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0003_auto_20181216_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedente',
            name='cpf_cnpj',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sacado',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
    ]
